/** Curated angles for automated blog generation — extend or edit anytime. */
export const BLOG_AI_TOPIC_SEEDS: readonly string[] = [
  "Practical tips for Go error handling patterns beginners miss",
  "How Python list comprehensions compare to explicit loops for readability",
  "Rust ownership vs borrowing: mental model for developers from GC languages",
  "TypeScript utility types (Partial, Pick, Omit) with real API-shaping examples",
  "Java records vs classes: when to use which in modern codebases",
  "C++ smart pointers (unique_ptr, shared_ptr) without drowning in jargon",
  "C# async/await pitfalls and ConfigureAwait in library code",
  "SQL window functions explained with a single running-example dataset",
  "JavaScript closures in event handlers: common bugs and fixes",
  "Structuring small CLI tools in Go: flags, stdin, and exit codes",
  "Python virtual environments and dependency pinning for solo projects",
  "Rust Result and Option: designing functions that fail clearly",
  "From JavaScript to TypeScript: incremental adoption in a brownfield app",
  "Java streams vs classic for-loops: performance myths and readability",
  "Modern C++ ranges and when they simplify iteration",
  "LINQ in C#: deferred execution gotchas",
  "SQL indexes: when they help and when they hurt writes",
  "Debouncing vs throttling in browser JavaScript",
  "Go interfaces: small interfaces and test doubles",
  "Python dataclasses and immutability patterns",
  "Rust lifetimes in function signatures without lifetime elision",
  "TypeScript discriminated unions for API response shapes",
  "Java Optional: proper use vs overuse",
  "C++ move semantics in everyday code",
  "C# pattern matching on records and switch expressions",
  "SQL transactions and isolation levels in plain language",
  "JavaScript modules: ESM vs CJS interop basics",
  "Go context cancellation for HTTP handlers and workers",
  "Python type hints for JSON payloads and pydantic-style thinking",
  "Rust testing: unit vs integration tests in a small crate",
  "TypeScript strictNullChecks: migration tips",
  "Java concurrency: ExecutorService vs virtual threads (conceptual)",
  "C++ constexpr and compile-time computation intro",
  "C# dependency injection minimal example for console apps",
  "SQL anti-patterns: SELECT * in production queries",
  "JavaScript Map vs Object for dynamic keys",
  "Go HTTP client timeouts and context deadlines",
  "Python asyncio: when not to use it",
  "Rust traits vs interfaces in other languages",
  "TypeScript satisfies operator for config objects",
  "Java serialization pitfalls and safer alternatives overview",
  "C++ const correctness for APIs",
  "C# Span and Memory for performance-sensitive paths (high level)",
  "SQL EXPLAIN basics for slow queries",
  "JavaScript WeakMap and private data patterns",
  "Go table-driven tests",
  "Python packaging: pyproject.toml at a glance",
  "Rust cargo workspaces for multi-crate repos",
  "TypeScript declaration merging when it helps",
  "Java module system (JPMS) mental model for app developers",
  "C++ RAII for resource management",
  "C# nullable reference types migration notes",
  "SQL NULL semantics that trip up joins",
  "JavaScript Temporal API direction (conceptual, no version hype)",
  "Go slices vs arrays: gotchas for new learners",
  "Python iterators and generators for large data",
  "Rust async runtime basics without picking a favorite crate war",
  "TypeScript narrowing with typeof and in",
  "Java exceptions: checked vs unchecked cultural divide",
  "C++ STL algorithms vs raw loops readability",
  "C# source generators: what problem they solve (overview)",
  "SQL common table expressions vs subqueries readability",
  "JavaScript fetch error handling and HTTP status codes",
  "Go race detector: when to run it",
  "Python pathlib vs os.path for file workflows",
  "Rust macros: when to avoid them as a beginner",
  "TypeScript branded types for domain primitives",
  "Java garbage collection pauses: what developers should know casually",
  "C++ undefined behavior examples everyone should recognize",
  "C# minimal APIs vs controllers for small services",
  "SQL full-text search vs LIKE for beginners",
  "JavaScript security: innerHTML vs textContent mindset",
  "Go workspace mode for multi-module repos (conceptual)",
  "Python logging vs print in small scripts",
  "Rust error crates: thiserror-style thinking without library lock-in",
  "TypeScript project references for monorepos (overview)",
  "Java JUnit 5 parameterized tests idea",
  "C++ namespaces and ADL gotchas (gentle intro)",
  "C# IAsyncEnumerable streaming results",
  "SQL materialized views when they help (conceptual)",
];

function shuffle<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function pickBlogAiTopics(count: number): string[] {
  const n = Math.max(0, Math.min(count, BLOG_AI_TOPIC_SEEDS.length));
  return shuffle([...BLOG_AI_TOPIC_SEEDS]).slice(0, n);
}
